name: CI

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master

jobs:
  ci:
    - name: 'Install -> Lint -> Test -> Build'
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [16.x]

  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install pnpm (pnpm 7)
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 7

    - name: Set node version to ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Lint
      run: pnpm lint

    # - name: Test
    #     run: pnpm test

    - name: Build
      run: pnpm build
